import Head from 'next/head'
import Image from 'next/image'
import tw from "tailwind-styled-components"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Hello everyone!</h1>
      </Main>
    </div>
  )
}

const Main = tw.main`
  p-10
`;
