import Head from "next/head";
import tw from "twin.macro";
import styled from "styled-components/macro";
import { HiViewGrid } from "react-icons/hi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Nav>
          <a href="http://">About</a>
          <a href="http://">Store</a>
        </Nav>
        <Nav>
          <a href="http://">Gmail</a>
          <a href="http://">Images</a>
          <HiViewGrid />
          <Avatar src="https://i.pinimg.com/originals/9c/ed/a5/9ceda5c51c58c4a447fb59038b4832be.jpg" />
        </Nav>
      </Header>
    </div>
  );
}

const Header = styled.header`
  ${tw`flex justify-between items-center text-sm text-gray-700`}
`;

const Nav = styled.nav`
  ${tw`flex space-x-4 items-center p-4`}

  > a {
    ${tw`hover:underline`}
  }

  > svg {
    ${tw`h-6 w-6 p-1 transform scale-150 rounded-full hover:bg-gray-100 cursor-pointer transition`}
  }
`;

const GridIcon = styled(HiViewGrid)`
  ${tw`h-6 w-6 p-1 transform scale-150 rounded-full hover:bg-gray-100 cursor-pointer transition`}
`;

const Avatar = styled.img`
  ${tw`rounded-full h-10 cursor-pointer`}
  ${tw`transition transform hover:scale-110`}
`;
