import Head from "next/head";
import styled from "styled-components/macro";
import tw from "twin.macro";

const search = (props) => {
  return (
    <>
      <Head>
        <title>Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>Search Results</Container>
    </>
  );
};

const Container = styled.div`
  ${tw``}
`;

export default search;
